### PR TITLE
strip caption property as is done with config caption

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Otherwise the tests are failing with the latest rakudo. See https://gist.github.com/Whateverable/ca337853fc2fe8640bdd6576c82f7969.

**Comment by autarch** [comment]
This fix isn't really good coding style since it repeats the substitution code twice. The right way to do this is to get `$caption` populated first, then substitute it if needed.

**Comment by autarch** [comment]
Actually, the whole substitution thing may also be wrong. IIRC (which I may not), I had to do it because of the bug I was working around. Now that P6 has fixed the bug, it'd be good to check if captions end up with spurious quotes around them. I'm guessing not.

**Comment by AlexDaniel** [comment]
IIRC it is not fixed yet.

**Comment by autarch** [comment]
That's unfortunate, since there's no way to know if the quotes are intentional or not. Once it's fixed this code will be broken.

**Comment by tbrowder** [comment]
I should have a POD quote fix for review in a day or two (given no major Christmas interuptions).

**Comment by lizmat** [comment]
Closing this now, as it appears to be inconclusive (and 4.5 years old).  Please re-open or make a new PR if you disagree.

**Pull request closed without merging**
